//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogCollections
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        public long artist_ID { get; set; }
        public long album_ID { get; set; }
        public string album_title { get; set; }
    
        public virtual artist artist { get; set; }
    }
}
