//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogCollections
{
    using System;
    using System.Collections.Generic;
    
    public partial class tv_episodes
    {
        public long show_id { get; set; }
        public long episode_ID { get; set; }
        public string episode_name { get; set; }
    
        public virtual tv_shows tv_shows { get; set; }
    }
}
